---
title: "Project"
author: "Jack"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup}
knitr::opts_chunk$set(warning = FALSE)
```

```{r}
setwd("C:/Users/jackw/Documents/R/ma575-project")
# install.packages("car")
# install.packages("ggplot")
library(car)
library(ggplot2)
# library(GGally)
```


```{r}
library(readr)
facebook <- read_delim("dataset_Facebook.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE)
# View(facebook)
```

```{r}
facebook <- na.omit(facebook)

# type
facebook$`Type` <- factor(facebook$`Type`)
str(facebook$`Type`)

# month
month_names <- c("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December")
facebook$`Post Month` <- factor(facebook$`Post Month`, levels = 1:12, labels = month_names)
str(facebook$`Post Month`)

# likes
facebook$like[is.na(facebook$like)] <- 0
facebook$like[is.na(facebook$like=='-Inf')] <- 0
facebook$log_like <- NA
facebook$log_like <- log(facebook$`like`)

plot(density(facebook$`Page total likes`))

facebook$lt_post_tot_reach <- NA
facebook$lt_post_tot_reach <- log(facebook$`Lifetime Post Total Reach`)
plot(density(facebook$lt_post_tot_reach))

facebook <- na.omit(facebook)
facebook <- facebook[is.finite(facebook$`Lifetime Post Total Reach`) & is.finite(facebook$log_like) & is.finite(facebook$`Page total likes`), ]

lm_model <- lm(lt_post_tot_reach ~ `Type` + `Post Month` + log_like + `Page total likes` + I(log_like^2), data = facebook)

summary(lm_model)
plot(lm_model)
vif(lm_model)
```

```{r}
# str(facebook)

facebook$Paid <- as.factor(facebook$Paid)

# post reach
facebook$log_ltpostreach <- NA
facebook$log_ltpostreach <- log(facebook$`Lifetime Post reach by people who like your Page`)
plot(density(facebook$log_ltpostreach))

# likes
facebook$like[is.na(facebook$like)] <- 0
facebook$log_like <- NA
facebook$log_like <- log(facebook$`like`)
plot(density(facebook$log_like))

# workday
facebook$hours_factor <- ifelse(facebook$`Post Hour` >= 9 & facebook$`Post Hour` < 17, "Work", "Non-Work")
facebook$hours_factor <- factor(facebook$hours_factor, levels = c("Work", "Non-Work"))

# total interactions
facebook$log_tot_interact <- NA
facebook$log_tot_interact <- log(facebook$`Total Interactions`)
plot(density(facebook$log_tot_interact))

facebook <- na.omit(facebook)
facebook <- facebook[is.finite(facebook$share) & is.finite(facebook$log_ltpostreach) & is.finite(facebook$log_like), ]

lm_model3 <- lm(share ~ log_like + log_tot_interact + hours_factor, data = facebook)

residuals_lm <- residuals(lm_model3)
threshold <- 50 
high_residuals <- which(abs(residuals_lm) > threshold)
facebook_cleaned <- subset(facebook, !row.names(facebook) %in% high_residuals)
lm_model_cleaned <- lm(share ~  log_tot_interact + log_like + hours_factor, data = facebook_cleaned)

summary(lm_model_cleaned)
plot(lm_model_cleaned)
```